import { Product } from '@/types';

export const WEB_APP_TITLE = 'B-EC';
export const WEB_APP_DESCRIPTION =
  'B-EC is a platform for buying and selling products online';

export const ROUTES = {
  INTERIOR: {
    path: '/interior',
    label: 'INTERIOR',
    categories: ['Living Room', 'Bedroom', 'Kitchen', 'Bathroom', 'Office'],
  },
  GARDEN: {
    path: '/garden-patio',
    label: 'GARDEN & PATIO',
    categories: ['Furniture', 'Plants', 'Decor', 'Lighting', 'Outdoor'],
  },
  SEARCH: {
    path: '/search',
    label: 'Search',
  },
  ACCOUNT: {
    path: '/account',
    label: 'Account',
  },
  WISHLIST: {
    path: '/wishlist',
    label: 'Wishlist',
  },
  CART: {
    path: '/cart',
    label: 'Shopping Cart',
  },
} as const;

export const products: Product[] = [
  {
    id: 1,
    name: 'Elegant Minimalist Sofa',
    price: 799.99,
    image: 'https://images.pexels.com/photos/4352247/pexels-photo-4352247.jpeg',
    category: 'Living Room',
    mainCategory: 'INTERIOR',
    description: 'An elegant minimalist sofa perfect for adding a touch of elegance to your living space.  Features plush cushions and a sturdy wooden frame.',
    rating: 4.5,
    stock: 15,
    discount: 0,
  },
  {
    id: 2,
    name: 'Modern Minimalist Chair',
    price: 449.50,
    image: 'https://images.pexels.com/photos/16804491/pexels-photo-16804491/free-photo-of-armchair-floor-lamp-and-a-houseplant-standing-in-a-corner.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Living Room',
    mainCategory: 'INTERIOR',
    description: 'A sleek and modern chair designed for minimalist aesthetics. Made from durable metal with a powder-coated finish.',
    rating: 4.2,
    stock: 8,
    discount: 10,
  },
  {
    id: 3,
    name: 'Rustic Wooden Dining Table Chair',
    price: 599.00,
    image: 'https://images.pexels.com/photos/29350087/pexels-photo-29350087/free-photo-of-stylish-wooden-armchair-with-textured-walls.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Kitchen',
    mainCategory: 'INTERIOR',
    description: 'A charming rustic dining table chair crafted from solid wood. Perfect for family meals and gatherings.',
    rating: 4.8,
    stock: 22,
    discount: 5,
  },
  {
    id: 4,
    name: 'Contemporary Bathroom Vanity',
    price: 329.75,
    image: 'https://images.pexels.com/photos/30036761/pexels-photo-30036761/free-photo-of-stylish-woven-design-cabinet-with-decorative-vases.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Bathroom',
    mainCategory: 'INTERIOR',
    description: 'A stylish bathroom vanity with a modern design.  Features ample storage space and a durable countertop.',
    rating: 4.0,
    stock: 10,
    discount: 0,
  },
  {
    id: 5,
    name: 'Ergonomic Office Chair',
    price: 1249.99,
    image: 'https://images.pexels.com/photos/7195522/pexels-photo-7195522.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Office',
    mainCategory: 'INTERIOR',
    description: 'A comfortable and supportive ergonomic office chair. Designed for long hours of work with adjustable features.',
    rating: 4.6,
    stock: 30,
    discount: 15, 
  },
  {
    id: 6,
    name: 'Patio Furniture Set',
    price: 899.00,
    image: 'https://images.pexels.com/photos/17472915/pexels-photo-17472915/free-photo-of-minimalist-cafe-and-restaurant-to-relax-estheticians.png?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Furniture',
    mainCategory: 'GARDEN',
    description: 'A beautiful wicker patio furniture set perfect for outdoor relaxation.',
    rating: 4.3,
    stock: 5,
    discount: 0,
  },
  {
    id: 7,
    name: 'Succulent Plant Pot',
    price: 29.99,
    image: 'https://images.pexels.com/photos/8989203/pexels-photo-8989203.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Plants',
    mainCategory: 'GARDEN',
    description: 'A decorative pot for succulent plants.  Easy to care for and perfect for adding greenery to your space.',
    rating: 4.7,
    stock: 50,
    discount: 20, 
  },
  {
    id: 8,
    name: 'Outdoor String Light',
    price: 19.50,
    image: 'https://images.pexels.com/photos/15590451/pexels-photo-15590451/free-photo-of-light-bulb-on-string.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Lighting',
    mainCategory: 'GARDEN',
    description: 'A set of warm white outdoor light perfect for creating a cozy ambiance in your garden or patio.',
    rating: 4.4,
    stock: 40,
    discount: 0,
  },
  {
    id: 9,
    name: 'Decorative Patio Pillows Set',
    price: 14.99,
    image: 'https://images.pexels.com/photos/17145784/pexels-photo-17145784/free-photo-of-garden-furniture-with-cushions.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Decor',
    mainCategory: 'GARDEN',
    description: 'A set of decorative patio pillows to add a touch of fun to your outdoor space.',
    rating: 3.9,
    stock: 60,
    discount: 10,
  },
  {
    id: 10,
    name: 'Modern Floor Lamp',
    price: 129.00,
    image: 'https://images.pexels.com/photos/19714779/pexels-photo-19714779/free-photo-of-modern-floor-lamp-standing-in-an-empty-room.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Living Room',
    mainCategory: 'INTERIOR',
    description: 'A sleek and modern floor lamp with an adjustable head. Perfect for reading or adding ambient light to any room.',
    rating: 4.5,
    stock: 25,
    discount: 0,
  },
  {
    id: 11,
    name: 'Patio Hanging Chair Set',
    price: 2999.99,
    image: 'https://images.pexels.com/photos/13304232/pexels-photo-13304232.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Furniture',
    mainCategory: 'GARDEN',
    description: 'A set of patio hanging chairs perfect for adding a touch of elegance to your outdoor space.',
    rating: 5,
    stock: 2,
    discount: 0,
  },
  {
    id: 12,
    name: 'Original Hammock',
    price: 1999.99,
    image: 'https://images.pexels.com/photos/14524375/pexels-photo-14524375.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Outdoor',
    mainCategory: 'GARDEN',
    description: 'An elegant original hammock perfect for adding a touch of elegance to your outdoor space.',
    rating: 5,
    stock: 2,
    discount: 0,
  },
  {
    id: 13,
    name: 'Outdoor Sofa',
    price: 1999.99,
    image: 'https://images.pexels.com/photos/16318706/pexels-photo-16318706/free-photo-of-white-bench-and-wall.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Furniture',
    mainCategory: 'GARDEN',
    description: 'An elegant outdoor sofa perfect for adding a touch of elegance to your outdoor space.',
    rating: 5,
    stock: 2,
    discount: 0,
  },
  ];